#+TITLE: Towards a great Developer Experience
#+AUTHOR: Andreas Pauley & Kevin Trethewey
#+DATE: 13 March 2018
#+REVEAL_THEME: sky
#+REVEAL_TRANS: default
#+OPTIONS: toc:nil, reveal_title_slide:nil, num:nil

* How do you create a great environment for developers?

 5 things we are learning along the Jemstep journey

* Introduction
In 2016 a small South African startup with 18 employees in total was acquired by Invesco,
an investment management company with $970 billion Assets Under Management.

#+REVEAL: split

Two years later, and Jemstep has grown from a team of 18 people to about 90, spread across 4 continents.

* Where we came from (2016)

#+ATTR_REVEAL: :frag (appear)
  - About 200,000 lines of (mostly) Scala code
  - Automated build pipelines, with automated deployments
  - Automated deployments about once per day, triggered by QA
  - 18 people: 5 developers, 2 testers, some investment specialists, product
    managers, customer support

* What we are learning about our Developer Experience

* Thing 1

If you really want to impress people, add the words “blockchain” to the end of
everything you say, blockchain.

* Thing 2

Before you criticize someone, walk a mile in their shoes. That way you are a
mile away from them and you have their shoes.


* Thing 3

“Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll
be warm for the rest of his life.”


* Thing 4

Laurie got offended that I used the word “puke.”
But to me, that's what her dinner tasted like.

* Thing 5

When I die, I want to die peacefully, in my sleep, like my grandpa did. Not like
the screaming passengers in his car.

* What we struggle with

* What we are focusing on now

* Where to next?

* Summary

#+ATTR_REVEAL: :frag (appear)
  1. Thing 1
  2. Thing 2
  3. Thing 3
  4. Thing 4
  5. Thing 5

* Conclusion
:PROPERTIES:
:reveal_background: ./images/forest-gnome.jpeg
:reveal_background_trans: slide
:END:
